movieproject/credentialsapp/urls.py
from django.urls import path

from . import views

app_name='credentialsapp'
urlpatterns = [

    path('registrations/',views.registrations,name='registrations'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/<int:id>/',views.updateProfile,name='update'),
]

movieproject/movieapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views
app_name='movieapp'

urlpatterns=[
    path('',views.allMovieCat,name='allMovieCat'),
    path('add/',views.addMovie,name='add'),
    path('mymovies/',views.myMovies,name='myMovies'),
    path('<slug:c_slug>/',views.allMovieCat,name='movies_by_category'),
    path('<slug:c_slug>/<slug:p_slug>',views.movieDetail,name='movieDetail'),
    path('updateMovie/<int:id>/',views.updateMovie,name='updateMovie'),
    path('delete/<int:id>/',views.deleteMovie,name='delete'),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movieapp/',include('movieapp.urls')),
    path('credentialsapp/',include('credentialsapp.urls')),
    path('search/',include('searchapp.urls')),
    path('userreviewapp/',include('userreviewapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/searchapp/urls.py
from django.urls import path
from . import views
app_name='searchapp'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

movieproject/userreviewapp/urls.py
from django.urls import path
from . import views
app_name='userreviewapp'

urlpatterns = [
    path('dispReview/',views.dispReview,name='dispReview'),
    path('addReview/',views.addReview,name='addReview'),
]

movieproject/templates/add.html
{% extends 'base.html' %}
{% block content %}
<h1 style="text-align:center;">Add Movie</h1>
<form action="{% url 'movieapp:add' %}" method="post"  enctype="multipart/form-data" >
    {% csrf_token %}
    <table align="center" border="">
        <tr>
            <td>
                <label>Movie Name:</label>
            </td>
            <td>
                <input type="text" name="name" placeholder="Enter Movie Name"><br>
            </td>
        </tr>
        <tr>
            <td>
                <label>Description:</label>

            </td>
            <td>
                <input type="text" name="desc" placeholder="Enter Movie Description"><br>
            </td>
        </tr>
        <tr>
            <td>
                <label>Release Date:</label>

            </td>
            <td>
                <input type="date" name="rel_date" placeholder="Enter Date of Release"><br>
            </td>
        </tr>
        <tr>
            <td>
                <label>Cast:</label>

            </td>
            <td>
                <input type="text" name="cast" placeholder="Enter Actors Name"><br>
            </td>
        </tr>
        <tr>
            <td>
                <label>Category:</label>
            </td>
            <td>
            <select name="genre" id="genre">
                {% for cat in links %}
                <option value="{{cat.name}}">{{cat.name}}</option>
                 {% endfor %}
            </select>
            </td>
        </tr>
        <tr>
            <td>
               <label>Poster:</label>

            </td>
            <td>
                 <input type="file" name="img"><br>
            </td>
        </tr>
        <tr>
            <td>
               <label>Trailer:</label>
            </td>
             <td>
                <input type="text" name="trailer" placeholder="Paste the Trailer link"><br>
            </td>
        </tr>
        <tr>
            <td>
                <input type="hidden" name="uid" value="{{request.user.id}}">
            </td>
             <td>
                <input type="submit">
            </td>
        </tr>
    </table>
</form>
<br><br><br><br><br><br><br><br>
<br><br><br><br>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;1,800&family=Protest+Guerrilla&family=Rubik:wght@500&family=Workbench&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/83049876d9.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}Movie Website and Recommendation Platform{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>


    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
{% include 'footer.html' %}
</html>

movieproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc|truncatewords:150 }}
    {% else %}
        Welcome to movie store.
    {% endif%}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name}} -movie
    {% else %}
        Movie Website and Recommendation Platform
    {% endif%}
{% endblock %}
{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p>
                        <a href="{% url 'movieapp:allMovieCat' %}">Home</a>
                    </p>
                </div>
            </div>
        </div>
    {% endif %}
    <div>
    <img src="{% static 'img/banner.png' %}" alt="our products" width="1400" height="500">
    </div>

    <div>
        <h1 class="text-center my_title">Our Movie Collections</h1>

    </div>



<div class="container">
    <div class="row">

        {% if movies.object_list %}
                {% for movie in movies.object_list %}
                <div class="col-md-4" style="padding:5px;">
                    <div class="card" style="width:150">
                    <a href="{{movie.get_url}}"><img src="{{movie.image.url}}" alt="{{movie.name}}" style="height:300px;width:100%"></a>
                        <div class="card-body">
                            <h4>
                                {{movie.name}}
                            </h4>
                        </div>
                    </div>
                </div>
                {% endfor %}
        {% else %}
           <div class="row mx-auto">
                <p class="text-center my_search_text">You have no movies right now.Kindly upload movies.</p>
            </div>
        {% endif %}


    </div>
    <div class="mx_auto">
            {% if movies.paginator.num_pages > 1 %}
            <hr>
        <div class="text-center">
                {% for pg in movies.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}" >{{pg}}</a>
                {% endfor %}
        </div>
            {% endif %}
    </div>




        <br>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    Do you want to delete this movie?<input type="submit">

</form>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Update Movie</h1>
<div>
<form method="post">
    {% csrf_token %}
    {{ fm.as_p }}
    <button type="submit">Update</button>
</form>
</div>
{% endblock %}

movieproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <footer class="mt-auto">
    <p class="text-center">
        &copy; RKM tech pvt ltd.All Rights reserved.
    </p>
        </footer>
</div>

movieproject/templates/header.html
{% load static %}
<header>
    <center>
    <a href="{% url 'movieapp:allMovieCat' %}"></a> <img src="{% static 'img/logo.png' %}" alt="logimage" width="100" height="100">
    </center>
</header>

movieproject/templates/movie.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ Movie.pdesc|truncatewords:150 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ movie.name}}
    {% endif%}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p>

        </p>
    </div>
</div>
<div class="container">
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{movie.image.url}}" alt="{{movie.name}}" style="width:100%;">
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_mov_title">{{movie.name}}</h1>
            <p class="my_title">Movie Description</p>
            <p class="text-justify my_mov_text">{{movie.desc}}</p>
            <p class="my_title">Movie Cast</p>
            <p class="text-justify my_mov_text">{{movie.cast}}</p>
            <p class="my_title">Released on</p>
            <p class="text-justify my_mov_text">{{movie.rel_date}}</p>
            <p class="my_title">Genre</p>
            <p class="text-justify my_mov_text">{{movie.category}}</p>
            <p class="my_title">Trailer</p>
            <a href="{{movie.trailer}}">Click to view trailer</a><br><br>

        </div>
        <br><br>


    </div>
</div>
</div>
<br> <br> <br> <br> <br><br> <br>
{% endblock %}

movieproject/templates/mymovies.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
{% endblock %}
{% block content %}

<div>
    <div class="row my_row_class">
        <div class="mx-auto">
            <p>
                <a href="{% url 'movieapp:allMovieCat' %}">Home</a>
            </p>
        </div>
    </div>
</div>

<div>
    <h1 class="text-center my_title">My Uploads</h1>
</div>

<div class="container">
<!--        <div class="row mx-auto">-->
<!--                <p class="text-center my_search_text">You have no movies right now.Kindly upload movies.</p>-->
<!--        </div>-->

    <div class="row">
        {% if movies %}
            {% for movie in movies %}
            <div class="col-md-4" style="padding:5px;">
                <div class="card" style="width:150">
                        <a href="{{movie.get_url}}"><img src="{{movie.image.url}}" alt="{{movie.name}}" style="height:300px;width:100%"></a>
                        <div class="card-body">
                            <h4>
                            {{movie.name}}
                <a class="btn btn-warning" href="{% url 'movieapp:updateMovie' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
                            </h4>
                        </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">You have no movies right now.Kindly upload movies.</p>
            </div>
        {% endif %}
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

movieproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <b><a class="nav-link" href="#" style="color:red;">MovieStore</a></b>
        </li>
        <b><li class="nav-item dropdown {% if 'movieapp' in request.path %} active {% endif %}">
         <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
         </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movieapp:allMovieCat' %}">All Movies</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li></b>
        <b><li class="nav-item dropdown  ">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'credentialsapp:update' user.id %}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'credentialsapp:logout' %}">Logout</a></li>
          </ul>
        </li></b>
        <li class="nav-item">
               <b><a class="nav-link" href="{% url 'movieapp:add' %}">Add Movie</a></b>
        </li>
        <li class="nav-item">
                <b><a class="nav-link" href="{% url 'movieapp:myMovies' %}">Your Collections</a></b>
        </li>
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'userreviewapp:dispReview' %}">Lets Discuss</a></b>
        </li>


      </ul>
      {% else %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <b><a class="nav-link" href="#" style="color:red;">MovieStore</a></b>
        </li>
        <b><li class="nav-item dropdown {% if 'movieapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movieapp:allMovieCat' %}">All Movies</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li></b>
        <b><li class="nav-item">
                <a class="nav-link" href="{% url 'credentialsapp:registrations' %}">Register</a>
        </li></b>
        <b><li class="nav-item">
                <a class="nav-link" href="{% url 'credentialsapp:login' %}">Login</a>
         </li></b>
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'userreviewapp:dispReview' %}">Lets Discuss</a></b>
        </li>

      </ul>
      {% endif %}
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
    </div>
  </div>
</nav>

movieproject/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        Welcome to RKM wholesale ecom store.

{% endblock %}
{% block title %}
Movie Website and Recommendation Platform

{% endblock %}
{% block content %}
<h1 style="text-align:center">Registration Form</h1>
<form action="{% url 'credentialsapp:registrations' %}" method='post'>
    {% csrf_token %}
    <table align="center" >
        <tr>
            <td>
                <input type="text" name="username" placeholder="Enter the username">
            </td>
        </tr>
        <tr>
            <td>
                <input type="text" name="firstname" placeholder="Enter the firstname">
            </td>
        </tr>
        <tr>
            <td>
                <input type="text" name="secondname" placeholder="Enter the lastname">
            </td>
        </tr>
        <tr>
            <td>
                <input type="email" name="email" placeholder="Enter the email">
            </td>
        </tr>
        <tr>
            <td>
                <input type="password" name="password" placeholder="Enter the password">
            </td>
        </tr>
        <tr>
            <td>
                <input type="password" name="confirmpaswword" placeholder="Please confirm password">
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit">
            </td>
        </tr>
    </table>
</form>
{% if profile_created %}
    <div style="text-align:center">
        <p>Profile created successfully,Please Proceed to Login</p>

    </div>
{% endif %}
{% for msg in messages %}
{{msg}}
{% endfor %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

movieproject/templates/review.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div>
		<div>
			{% if user.is_authenticated %}
			<form action="{% url 'userreviewapp:addReview' %}" method='post'>
				{% csrf_token %}
				<table align="center" >
					<tr>
						<td>
							<input type="text" name="desc" placeholder="Enter your comments">
						</td>
						<td>
							<input type="submit">
						</td>
					</tr>
				</table>
			</form>
			{% endif %}
		</div>
	</div>
</div>
</div>
<div>
<div class="container bootstrap snippets bootdey">
    <div class="row">
		<div class="col-md-12">
		    <div class="blog-comment">
				<h3 class="text-success">Reviews or Comments</h3>
                <hr/>
				<ul class="comments">
					{% for rv in review %}
						<li class="clearfix">
						  <div class="post-comments">
							  <p class="meta">{{rv.created}}</p>
							  <p>{{rv.uname}} says :</p>
							  <p>
								  {{rv.desc}}
							  </p>
						  </div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
<br><br><br><br><br><br><br><br><br><br>
{% endblock %}

movieproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="width:250px;height:250px;">
            <a href="{{movie.get_url}}"><img class="card-img-top my_image" src="{{movie.image.url}}" alt="{{movie.name}}" style="width:250px;height:250px;"></a>
                <div class="card-body">
                    <h4>

                        {{movie.name}}|{{movie.category}}
                    </h4>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">Movie not found</p>
            </div>
{% endfor %}
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

movieproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<h1>Your Profile</h1>
<div>
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    <button type="submit">Update</button>

  </form>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}